'use strict';
let state=Engine.defaults(),group='air',active='base';
const $=s=>document.querySelector(s),node=(tag,cls,text)=>{const e=document.createElement(tag);if(cls)e.className=cls;if(text!==undefined)e.textContent=text;return e;};
function fmt(v){if(v==null)return '待確認';if(!Number.isFinite(v))return '無有效結果';if(v===0)return '0';if(Math.abs(v)<.001||Math.abs(v)>=1e9)return v.toExponential(5);return v.toLocaleString('zh-TW',{maximumSignificantDigits:6});}
function renderNav(){const nav=$('#modules');nav.replaceChildren();Engine.sections.filter(s=>s.group===group).forEach(s=>{const b=node('button',s.id===active?'active':'',s.title);b.setAttribute('aria-current',s.id===active?'page':'false');b.onclick=()=>{active=s.id;render();};nav.append(b);});document.querySelectorAll('[data-group]').forEach(b=>{b.classList.toggle('active',b.dataset.group===group);b.setAttribute('aria-pressed',String(b.dataset.group===group));});}
function modeFields(){if(!['water','gas'].includes(active))return;for(const k of ['flow','tout']){const input=$(`#input-${active}-${k}`),disabled=k==='flow'?Number(state[active].mode)===0:Number(state[active].mode)===1;input.disabled=disabled;input.closest('.field').classList.toggle('disabled',disabled);}}
function render(){renderNav();const s=Engine.sections.find(s=>s.id===active);$('#title').textContent=s.title;$('#note').textContent=s.note;$('#module-number').textContent=String(Engine.sections.filter(a=>a.group===group).indexOf(s)+1).padStart(2,'0');const form=$('#inputs');form.replaceChildren();form.onsubmit=e=>e.preventDefault();for(const f of s.fields){const wrap=node('div','field'),label=node('label','',f.label),row=node('div','input-row'),id=`input-${active}-${f.key}`;label.htmlFor=id;let input;if(f.unit==='開關'||f.unit==='冷側模式'){input=node('select');const options=f.unit==='開關'?[[1,'納入'],[0,'不納入']]:[[0,'指定冷側出口溫度'],[1,'指定冷側流量']];for(const [v,t] of options){const o=node('option','',t);o.value=v;input.append(o);}}else{input=node('input');input.type=f.unit==='文字'?'text':'number';input.step='any';input.min=f.min;input.max=f.max;input.inputMode=f.unit==='文字'?'text':'decimal';if(f.optional)input.placeholder='自動／未提供';}const suggestions=active==='bag'&&f.key==='cleaning'?['Pulse Jet','Reverse Air','Shaker']:active==='scrub'&&f.key==='pollutant'?['HCl','SO2','HF','NH3','H2S','VOC','PM']:active==='fan'&&f.key==='rated'?[.75,1.1,1.5,2.2,3,4,5.5,7.5,11,15,18.5,22,30,37,45,55,75,90,110,132,160,200,250]:null;if(suggestions){const list=node('datalist');list.id=id+'-options';for(const v of suggestions){const option=node('option');option.value=v;list.append(option);}input.setAttribute('list',list.id);wrap.append(list);}input.id=id;input.value=state[active][f.key];input.setAttribute('aria-label',f.label);input.oninput=()=>{state[active][f.key]=input.value;modeFields();results();};row.append(input);if(!['開關','冷側模式','文字'].includes(f.unit))row.append(node('span','',f.unit));wrap.append(label,row);form.append(wrap);}if(!s.fields.length)form.append(node('p','empty','依各設備的「納入系統」設定彙整。要修改條件，請選擇左側或上方的設備模組。'));modeFields();results();}
function results(){const r=Engine.calculate(state)[active],out=$('#result');out.replaceChildren();if(r.error){out.append(node('p','message error',r.error));return;}for(const a of r.rows){const row=node('div','result-row'),value=node('div','value',fmt(a.value));value.append(node('span','unit',a.unit));row.append(node('span','label',a.label),value);out.append(row);}for(const msg of r.notes)out.append(node('p','message',msg));}
document.querySelectorAll('[data-group]').forEach(b=>b.onclick=()=>{group=b.dataset.group;active=group==='air'?'base':'heat';render();});
$('#reset').onclick=()=>{const d=Engine.defaults();for(const s of Engine.sections.filter(s=>s.group===group))state[s.id]=d[s.id];$('#status').textContent='本工具已恢復範例值。';render();};
$('#save').onclick=()=>{const computed=Engine.calculate(state),exported={format:'besta-internal-v1',createdAt:new Date().toISOString(),inputs:state,results:Object.fromEntries(Object.entries(computed).map(([k,r])=>[k,{rows:r.rows,notes:r.notes,error:r.error}])),basis:'工程初估，限制與來源見 VALIDATION.md'};const url=URL.createObjectURL(new Blob([JSON.stringify(exported,null,2)],{type:'application/json'})),a=node('a');a.href=url;a.download=`besta-engineering-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);$('#status').textContent='已匯出兩套工具的輸入條件與計算結果；請將紀錄存放於內部位置。';};
$('#load').onclick=()=>$('#file').click();$('#file').onchange=async e=>{try{const f=e.target.files[0];if(!f)return;if(f.size>2e6)throw Error('檔案過大。');const data=JSON.parse(await f.text());if(data.format!=='besta-internal-v1')throw Error('不是本工具的計算紀錄。');const next=Engine.defaults();for(const s of Engine.sections)for(const f of s.fields){const v=data.inputs?.[s.id]?.[f.key];if(v===undefined||!['string','number'].includes(typeof v))throw Error('紀錄欄位不完整。');next[s.id][f.key]=v;}for(const s of Engine.sections)Engine.read(next,s.id);state=next;render();$('#status').textContent='已載入紀錄並重新計算。';}catch(err){$('#status').textContent=`無法載入：${err.message}`;}finally{e.target.value='';}};
render();
