/* Internal engineering screening models. See VALIDATION.md for scope and sources. */
(function(root){
'use strict';
const fields=(rows)=>rows.map(([key,label,value,unit,min=0,max=1e12,optional=false])=>({key,label,value,unit,min,max,optional}));
const sections=[
{id:'base',group:'air',title:'基本條件',note:'風量與濃度均使用入口實際狀態、相同乾濕基準。預設為空氣近似；非空氣廢氣請輸入實測密度與黏度。',fields:fields([
['q','入口實際風量',18000,'m³/h',.001],['t','入口溫度',60,'°C',0,200],['p','絕對壓力',101.325,'kPa',1,300],['mw','氣體平均分子量',28.97,'kg/kmol',1,200],['rho','密度覆寫（選填）','','kg/m³',.001,100,true],['mu','黏度覆寫（選填）','','Pa·s',1e-7,.01,true],['rh','相對濕度',60,'%',0,100],['pm','入口粒狀物濃度',1200,'mg/m³'],['rhop','粒子密度',2000,'kg/m³',1,50000],['dp','代表粒徑',10,'µm',.001,10000],['hours','每日運轉',16,'h/day',.01,24],['days','每年運轉',300,'day/year',1,366]])},
{id:'duct',group:'air',title:'風管',note:'圓管等徑、低速不可壓縮流近似。轉捩流不提供確定壓損，請調整尺寸或另作工程核算。',fields:fields([
['on','納入系統壓損',1,'開關',0,1],['v','設計風速',16,'m/s',.01,100],['diameter','實際內徑（選填）','','m',.001,50,true],['length','直管總長',30,'m'],['rough','絕對粗糙度',.15,'mm',0,100],['k','局部阻力係數合計',5,'—']])},
{id:'cyclone',group:'air',title:'旋風集塵',note:'Lapple 簡化模型。代表粒徑效率僅針對該粒徑；串聯系統需另填粒徑分布加權或實測的總質量效率。',fields:fields([
['on','納入系統',1,'開關',0,1],['n','並聯台數',1,'台',1,1000],['v','入口風速',18,'m/s',.01,100],['a','入口高度／筒徑',.5,'—',.01,2],['b','入口寬度／筒徑',.2,'—',.01,2],['ne','有效圈數',5.5,'—',.01,100],['beta','分級曲線指數',2,'—',.01,10],['k','壓損係數',6.5,'—'],['eta','總質量效率（選填）','','%',0,100,true]])},
{id:'bag',group:'air',title:'袋式集塵',note:'過濾風速、效率、壓損及耐溫須依粉塵特性、濾材與清灰方式確認。模組出口濃度以基本條件為入口；串聯結果見系統總覽。',fields:fields([
['on','納入系統',1,'開關',0,1],['v','過濾風速',1.5,'m/min',.001,20],['d','濾袋直徑',.16,'m',.001,2],['l','濾袋長度',3,'m',.01,30],['margin','面積裕量',1.1,'倍',1,10],['eta','質量去除效率',99.5,'%',0,100],['loss','運轉壓損',1500,'Pa'],['tmax','濾材耐溫',180,'°C',0,1000]])},
{id:'esp',group:'air',title:'靜電集塵',note:'Deutsch–Anderson 理想化估算。有效移動速度須以粉塵、電阻率與設備試驗資料確認。',fields:fields([
['on','納入系統',1,'開關',0,1],['eta','目標去除效率',99,'%',.001,99.9999],['w','有效移動速度',.08,'m/s',.00001,10],['margin','集塵面積裕量',1.1,'倍',1,10],['loss','設備壓損',250,'Pa']])},
{id:'scrub',group:'air',title:'濕式洗滌塔',note:'HCl／NaOH 範例，計量比 1 mol/mol。填料高度採氣相平衡濃度近零的簡化 NTU；不適用所有吸收反應。',fields:fields([
['on','納入系統壓損',1,'開關',0,1],['cin','入口氣態污染物濃度',500,'mg/m³'],['mw','污染物分子量',36.46,'kg/kmol',1,1000],['eta','目標去除效率',95,'%',.001,99.9999],['v','塔內氣速',2,'m/s',.01,20],['lg','液氣比',1,'L/m³',.001,100],['htu','氣相總傳質單元高度',.6,'m',.001,100],['packing','單位填料壓損',250,'Pa/m'],['demist','除霧器壓損',200,'Pa'],['reagentMW','藥劑分子量',40,'kg/kmol',1,1000],['stoich','藥劑／污染物莫耳比',1,'mol/mol',.001,100],['util','藥劑利用率',80,'%',.001,100],['excess','藥劑過量倍率',1.2,'倍',1,100],['ph','操作 pH（記錄）',11,'—',0,14]])},
{id:'carbon',group:'air',title:'活性碳吸附',note:'容量法估算更換時間，不是突破時間保證。工作容量與折減係數應避免重複折減；需以實際 VOC、溫濕度的吸附資料確認。',fields:fields([
['on','納入系統壓損',1,'開關',0,1],['cin','入口 VOC 濃度',300,'mg/m³'],['eta','目標去除效率',90,'%',0,100],['v','表面風速',.3,'m/s',.001,10],['ebct','空床接觸時間',1,'s',.001,1000],['bulk','碳床堆積密度',480,'kg/m³',1,2000],['capacity','工作吸附容量',.08,'kg/kg',.00001,5],['util','額外容量折減係數',70,'%',.001,100],['packing','單位床深壓損',800,'Pa/m'],['rhmax','相對濕度參考上限',60,'%',0,100]])},
{id:'fan',group:'air',title:'風機與馬達',note:'以基本條件的風量／密度估算。效率使用總壓效率，其他壓損應包含未回收的出口動壓。風機若位於降溫或加濕後，須用該處工況另算。',fields:fields([
['other','其他壓損與出口損失',300,'Pa'],['margin','壓力裕量',1.15,'倍',1,10],['eta','風機總壓效率',70,'%',.001,100],['drive','傳動效率',95,'%',.001,100],['motor','馬達效率',90,'%',.001,100],['rated','馬達額定軸輸出功率',45,'kW',.001]])},
{id:'stack',group:'air',title:'煙囪',note:'未填出口實際風量時，依相同氣體莫耳流量換算溫壓。加濕、冷凝、漏氣或反應改變氣量時，必須填出口實際風量。高度僅記錄，不代表擴散或法規核算。',fields:fields([
['t','出口溫度',35,'°C',0,1000],['p','出口絕對壓力',101.325,'kPa',1,300],['q','出口實際風量（選填）','','m³/h',.001,1e12,true],['v','出口風速',15,'m/s',.01,100],['height','煙囪高度（記錄）',20,'m',.01,1000]])},
{id:'summary',group:'air',title:'系統總覽',note:'粒狀物依旋風 → 袋濾 → 靜電的選取順序串聯。氣態污染物與 VOC 分別計算，不混為總去除率；各段暫採同一入口風量工況。',fields:[]},
{id:'heat',group:'heat',title:'廢氣冷凝熱負荷',note:'乾空氣＋水蒸氣、入口／出口皆飽和；定比熱理想混合氣初估，冷凝液以出口溫度排出。高溫高濕及非空氣組成須另作物性核算。',fields:fields([
['tin','廢氣入口溫度',90,'°C',.01,100],['tout','廢氣出口溫度',40,'°C',.01,100],['q','乾空氣標準風量',1000,'Nm³/h',.001],['p','絕對壓力',101.325,'kPa',10,200],['cpd','乾空氣定壓比熱',1.006,'kJ/(kg·K)',.1,10],['cpv','水蒸氣定壓比熱',1.86,'kJ/(kg·K)',.1,10],['cpl','液態水比熱',4.186,'kJ/(kg·K)',.1,10]])},
{id:'water',group:'heat',title:'氣水熱交換',note:'純逆流、定比熱與固定 U 的初估。面積採含冷凝液隨熱流排出的分段能量模型；需由設備廠確認 U、污垢、腐蝕與實際流型。',fields:fields([
['mode','已知條件',0,'冷側模式',0,1],['tin','冷卻水入口溫度',25,'°C',.01,99],['tout','冷卻水目標出口溫度',35,'°C',.01,99],['flow','已知冷卻水流量',20,'m³/h',.001],['cp','冷卻水比熱',4.186,'kJ/(kg·K)',.1,10],['rho','冷卻水密度',1000,'kg/m³',100,2000],['u','總傳熱係數 U',60,'W/(m²·K)',.001,10000]])},
{id:'gas',group:'heat',title:'氣氣熱交換',note:'冷側為乾空氣，Nm³ 基準為 0°C、101.325 kPa。純逆流、固定 U 初估；同時檢查內部溫差，不只檢查兩端。',fields:fields([
['mode','已知條件',1,'冷側模式',0,1],['tin','冷空氣入口溫度',20,'°C',-50,200],['tout','冷空氣目標出口溫度',60,'°C',-49,300],['flow','已知冷空氣標準風量',90000,'Nm³/h',.001],['cp','冷空氣定壓比熱',1.006,'kJ/(kg·K)',.1,10],['u','總傳熱係數 U',25,'W/(m²·K)',.001,10000]])}
];
// Record-only fields and original workbook property controls.
sections.find(s=>s.id==='bag').fields.splice(1,0,{key:'cleaning',label:'清灰方式（記錄）',value:'Pulse Jet',unit:'文字'});
sections.find(s=>s.id==='scrub').fields.splice(1,0,{key:'pollutant',label:'污染物名稱（記錄）',value:'HCl',unit:'文字'},{key:'reagent',label:'藥劑名稱（記錄）',value:'NaOH',unit:'文字'});
sections.find(s=>s.id==='heat').fields.push(...fields([['rhoN','乾氣體標準密度',1.2923190576466714,'kg/Nm³',.05,10]]));
sections.find(s=>s.id==='gas').fields.push(...fields([['rhoN','冷氣體標準密度',1.2923190576466714,'kg/Nm³',.05,10]]));
function defaults(){return Object.fromEntries(sections.map(s=>[s.id,Object.fromEntries(s.fields.map(f=>[f.key,f.value]))]));}
function read(state,id){const s=sections.find(s=>s.id===id), out={}; for(const f of s.fields){const raw=state[id]?.[f.key];if(f.unit==='文字'){assert(typeof raw==='string'&&raw.length>0&&raw.length<=100,f.label+'：請輸入 1–100 字。');out[f.key]=raw;continue;}if(['water','gas'].includes(id)&&((f.key==='flow'&&Number(state[id].mode)===0)||(f.key==='tout'&&Number(state[id].mode)===1))){out[f.key]=null;continue;}if(['開關','冷側模式'].includes(f.unit))assert(raw===0||raw===1||raw==='0'||raw==='1',f.label+'：請選擇有效選項。');if((raw===''||raw==null)&&f.optional){out[f.key]=null;continue;}const v=Number(raw);if(raw===''||raw==null||!Number.isFinite(v)||v<f.min||v>f.max)throw Error(`${f.label}：請輸入 ${f.min} 至 ${f.max} 的數值。`);out[f.key]=v;}if(id==='cyclone'&&!Number.isInteger(out.n))throw Error('並聯台數需為整數。');return out;}
function assert(ok,msg){if(!ok)throw Error(msg);}
const circle=a=>Math.sqrt(4*a/Math.PI);
function psat(c){assert(c>=.01&&c<=100,'飽和水物性範圍為 0.01–100°C。');const t=c+273.15,z=1-t/647.096;return 22064*Math.exp(647.096/t*(-7.85951783*z+1.84408259*z**1.5-11.7866497*z**3+22.6807411*z**3.5-15.9618719*z**4+1.80122502*z**7.5));}
function humidity(t,p,ratio=.621945){const s=psat(t);assert(s<p,'飽和蒸氣壓已達總壓，無法使用此濕空氣模型。請降低溫度或確認絕對壓力。');return ratio*s/(p-s);}
function lmtd(a,b){assert(a>0&&b>0,'溫差不足或發生溫度交叉，無法估算可行換熱面積。');return Math.abs(a-b)<1e-9*Math.max(a,b)?(a+b)/2:(a-b)/Math.log(a/b);}
function friction(re,e){assert(re>0&&e>=0,'雷諾數或粗糙度無效。');if(re<2000)return 64/re;assert(re>=4000,'風管處於轉捩流（Re 2,000–4,000），壓損需另外核算。');return .25/Math.log10(e/3.7+5.74/re**.9)**2;}
function heatModel(x){assert(x.tin>x.tout,'廢氣入口溫度必須高於出口溫度。');const rhoN=x.rhoN,ratio=18.015257/(rhoN*8.314462618*273.15/101.325),wi=humidity(x.tin,x.p,ratio),wo=humidity(x.tout,x.p,ratio),md=x.q*rhoN;
const h=t=>{const w=humidity(t,x.p,ratio);return x.cpd*t+w*(2501+x.cpv*t)+(wi-w)*x.cpl*t;};
const condensate=md*(wi-wo),sensible=md*(x.cpd+wi*x.cpv)*(x.tin-x.tout)/3600,latent=condensate*(2501+(x.cpv-x.cpl)*x.tout)/3600,q=md*(h(x.tin)-h(x.tout))/3600;
return {wi,wo,md,condensate,q,sensible,latent,h,rhoN,pin:psat(x.tin),pout:psat(x.tout)};}
function exchanger(hot,h,x,water,n=1000){const rho=water?x.rho:x.rhoN;let mass,tout;if(x.mode===0){assert(x.tout>x.tin,'冷側目標出口溫度必須高於入口。');tout=x.tout;mass=h.q*3600/(x.cp*(tout-x.tin));}else{mass=x.flow*rho;tout=x.tin+h.q*3600/(mass*x.cp);}if(water)assert(tout<100&&tout>0,'水側計算溫度超出液態水初估範圍（0–100°C）。');
const endLm=lmtd(hot.tin-tout,hot.tout-x.tin),base=h.h(hot.tout);let area=0,minDelta=Infinity,prevQ=0,prevDelta=hot.tout-x.tin;
for(let i=0;i<=n;i++){const t=hot.tout+(hot.tin-hot.tout)*i/n,q=h.md*(h.h(t)-base)/3600,tc=x.tin+q*3600/(mass*x.cp),delta=t-tc;assert(delta>0,'內部發生溫度交叉：請增加冷側流量、降低冷側入口或目標出口溫度。');minDelta=Math.min(minDelta,delta);if(i)area+=(q-prevQ)*1000/(x.u*lmtd(prevDelta,delta));prevQ=q;prevDelta=delta;}
return {mass,flow:mass/rho,tout,endLm,area,minDelta,endArea:h.q*1000/(x.u*endLm)};}
const EngineTitle=id=>sections.find(s=>s.id===id).title;
function calculate(state){const cache={};function get(id){if(cache[id]){if(cache[id].error)throw Error(cache[id].error);return cache[id];}try{const x=read(state,id),r={rows:[],notes:[]};const add=(label,value,unit='')=>r.rows.push({label,value,unit});let b;
if(['base','duct','cyclone','bag','esp','scrub','carbon','fan','stack','summary'].includes(id)&&id!=='base')b=get('base');
switch(id){
case'base':r.q=x.q/3600;r.rho=x.rho??x.p*x.mw/(8.314462618*(x.t+273.15));r.mu=x.mu??1.716e-5*((x.t+273.15)/273.15)**1.5*(273.15+111)/(x.t+273.15+111);r.pm=x.pm;r.load=x.q*x.pm/1e6;add('氣體密度',r.rho,'kg/m³');add('氣體動力黏度',r.mu,'Pa·s');add('實際體積流率',r.q,'m³/s');add('粒狀物質量流率',r.load,'kg/h');add('每日粒狀物',r.load*x.hours,'kg/day');add('每年粒狀物',r.load*x.hours*x.days,'kg/year');break;
case'duct':{const d=x.diameter??circle(b.q/x.v),v=b.q/(Math.PI*d*d/4),re=b.rho*v*d/b.mu;assert(x.rough/1000/d<.05,'相對粗糙度過大，超出此管流近似範圍。');assert(v<100,'實際風速達 100 m/s，需另作可壓縮流核算。');const f=friction(re,x.rough/1000/d),vp=b.rho*v*v/2;r.loss=(f*x.length/d+x.k)*vp;add('風管內徑',d,'m');add('所需設計截面積',b.q/x.v,'m²');add('實際截面積',Math.PI*d*d/4,'m²');add('速度壓',vp,'Pa');add('實際風速',v,'m/s');add('雷諾數',re);add('Darcy 摩擦係數',f);add('直管壓損',f*x.length/d*vp,'Pa');add('局部壓損',x.k*vp,'Pa');add('合計壓損',r.loss,'Pa');break;}
case'cyclone':{const base=read(state,'base');assert(base.rhop>b.rho,'粒子密度必須大於氣體密度。');const d=Math.sqrt(b.q/x.n/(x.v*x.a*x.b)),cut=Math.sqrt(9*b.mu*x.b*d/(2*Math.PI*x.ne*x.v*(base.rhop-b.rho)))*1e6;r.eta=x.eta==null?null:x.eta/100;r.loss=x.k*b.rho*x.v*x.v/2;add('單台筒徑',d,'m');add('單台風量',b.q/x.n,'m³/s');add('入口速度壓',b.rho*x.v*x.v/2,'Pa');add('單機出口 PM 濃度',r.eta==null?null:b.pm*(1-r.eta),'mg/m³');add('單機 PM 捕集量',r.eta==null?null:b.load*r.eta,'kg/h');add('入口高度',x.a*d,'m');add('入口寬度',x.b*d,'m');add('切割粒徑 d₅₀',cut,'µm');add('代表粒徑分級效率',100/(1+(cut/base.dp)**x.beta),'%');add('總質量效率',x.eta,'%');add('設備壓損',r.loss,'Pa');if(x.eta==null)r.notes.push('未提供總質量效率；不推算串聯出口濃度。');break;}
case'bag':{const net=b.q*60/x.v,design=net*x.margin,n=Math.ceil(design/(Math.PI*x.d*x.l));r.eta=x.eta/100;r.loss=x.loss;add('淨過濾面積',net,'m²');add('設計面積',design,'m²');add('濾袋數量',n,'支');add('單條濾袋面積',Math.PI*x.d*x.l,'m²');add('PM 捕集量',b.load*r.eta,'kg/h');add('實裝過濾面積',n*Math.PI*x.d*x.l,'m²');add('實際過濾風速',b.q*60/(n*Math.PI*x.d*x.l),'m/min');add('單機出口濃度',b.pm*(1-r.eta),'mg/m³');add('設備壓損',r.loss,'Pa');if(read(state,'base').t>x.tmax)r.notes.push('入口溫度超過所填濾材耐溫，須先降溫或更換濾材。');break;}
case'esp':{const a=-b.q/x.w*Math.log1p(-x.eta/100),design=a*x.margin;r.eta=-Math.expm1(-x.w*design/b.q);r.loss=x.loss;add('理論集塵面積',a,'m²');add('設計集塵面積',design,'m²');add('設計面積下預估效率',r.eta*100,'%');add('比集塵面積',design/b.q,'s/m');add('PM 捕集量',b.load*r.eta,'kg/h');add('單機出口濃度',b.pm*(1-r.eta),'mg/m³');add('設備壓損',r.loss,'Pa');break;}
case'scrub':{const ntu=-Math.log1p(-x.eta/100),height=ntu*x.htu,removed=b.q*3600*x.cin*x.eta/1e8;r.loss=height*x.packing+x.demist;add('塔徑',circle(b.q/x.v),'m');add('塔截面積',b.q/x.v,'m²');add('去除污染物莫耳流率',removed/x.mw,'kmol/h');add('理論純藥劑量',removed/x.mw*x.reagentMW*x.stoich,'kg/h');add('填料壓損',height*x.packing,'Pa');add('污染物去除量',removed,'kg/h');add('氣態污染物出口濃度',x.cin*(1-x.eta/100),'mg/m³');add('設計純藥劑量',removed/x.mw*x.reagentMW*x.stoich/(x.util/100)*x.excess,'kg/h');add('循環液量',b.q*3600*x.lg/1000,'m³/h');add('傳質單元數',ntu);add('填料高度',height,'m');add('設備壓損',r.loss,'Pa');break;}
case'carbon':{const a=b.q/x.v,depth=x.v*x.ebct,mass=b.q*x.ebct*x.bulk,removed=b.q*3600*x.cin*x.eta/1e8;r.loss=depth*x.packing;add('吸附塔直徑',circle(a),'m');add('碳床深度',depth,'m');add('碳床截面積',a,'m²');add('未折減容量使用時間',removed>0?mass*x.capacity/removed:null,'h');add('碳床體積',b.q*x.ebct,'m³');add('活性碳裝填量',mass,'kg');add('VOC 去除量',removed,'kg/h');add('VOC 出口濃度',x.cin*(1-x.eta/100),'mg/m³');add('折減後容量使用時間',removed>0?mass*x.capacity*x.util/100/removed:null,'h');add('估計運轉日數',removed>0?mass*x.capacity*x.util/100/removed/read(state,'base').hours:null,'day');add('設備壓損',r.loss,'Pa');if(removed===0)r.notes.push('無吸附負荷，不推算更換時間。');if(read(state,'base').rh>x.rhmax)r.notes.push('入口相對濕度超過參考上限，應重新確認吸附容量。');break;}
case'fan':{let loss=x.other;for(const m of ['duct','cyclone','bag','esp','scrub','carbon'])if(Number(state[m]?.on)===1)loss+=get(m).loss;r.pressure=loss*x.margin;r.baseLoss=loss;const air=b.q*r.pressure/1000,shaft=air/(x.eta/100),motorShaft=shaft/(x.drive/100);add('系統總壓需求',loss,'Pa');add('含裕量選型總壓',r.pressure,'Pa');add('氣體功率',air,'kW');add('風機軸功率',shaft,'kW');r.motorShaft=motorShaft;r.electric=motorShaft/(x.motor/100);add('馬達所需軸輸出',motorShaft,'kW');add('額定軸功率裕量',motorShaft>0?(x.rated/motorShaft-1)*100:null,'%');add('預估電力輸入',motorShaft/(x.motor/100),'kW');add('額定軸功率餘量',x.rated-motorShaft,'kW');if(x.rated<motorShaft)r.notes.push('所選馬達額定軸輸出不足。');break;}
case'summary':{let c=b.pm;for(const m of ['cyclone','bag','esp'])if(Number(state[m]?.on)===1){const e=get(m).eta;c=c==null||e==null?null:c*(1-e);}r.c=c;add('入口實際風量',b.q*3600,'m³/h');add('串聯粒狀物出口濃度',c,'mg/m³（入口工況）');add('串聯粒狀物去除效率',c==null||b.pm===0?null:(1-c/b.pm)*100,'%');add('粒狀物出口質量流率',c==null?null:c*b.q*3600/1e6,'kg/h');if(c==null)r.notes.push('請在旋風集塵填入總質量效率，或將該設備移出系統。');for(const m of ['cyclone','bag','esp']){if(Number(state[m]?.on)===1){const e=get(m).eta;add(EngineTitle(m)+' 階段效率',e==null?null:e*100,'%');}}let stage=b.pm;for(const m of ['cyclone','bag','esp']){if(Number(state[m]?.on)===1){const e=get(m).eta;stage=stage==null||e==null?null:stage*(1-e);add(EngineTitle(m)+' 階段出口',stage,'mg/m³');}}for(const m of ['duct','cyclone','bag','esp','scrub','carbon']){try{add(EngineTitle(m)+' 納入壓損',Number(state[m]?.on)===1?get(m).loss:0,'Pa');}catch(e){r.notes.push(e.message);}}try{const f=get('fan');add('系統基礎總壓損',f.baseLoss,'Pa');add('含裕量風機總壓',f.pressure,'Pa');add('最低馬達軸輸出',f.motorShaft,'kW');add('選定馬達軸輸出',read(state,'fan').rated,'kW');}catch(e){r.notes.push(e.message);}for(const m of ['scrub','carbon'])if(Number(state[m]?.on)===1){try{const rr=get(m);for(const row of rr.rows.filter(a=>['氣態污染物出口濃度','VOC 出口濃度','估計運轉日數'].includes(a.label)))r.rows.push(row);}catch(e){r.notes.push(e.message);}}break;}
case'stack':{const bs=read(state,'base'),q=x.q??bs.q*(x.t+273.15)/(bs.t+273.15)*bs.p/x.p,c=get('summary').c;add('出口實際風量',q,'m³/h');add('煙囪內徑',circle(q/3600/x.v),'m');add('出口截面積',q/3600/x.v,'m²');add('PM 排放量',c==null?null:c*bs.q/1e6,'kg/h');add('PM 年排放量',c==null?null:c*bs.q/1e6*bs.hours*bs.days,'kg/year');add('粒狀物出口濃度',c==null?null:c*bs.q/q,'mg/m³（出口工況）');add('粒狀物排放率',c==null?null:c*bs.q/3.6e6,'g/s');if(x.q==null&&Number(state.scrub.on)===1)r.notes.push('系統含洗滌塔：可能改變含水量，請填入出口實際風量再選型。');break;}
case'heat':{r.model=heatModel(x);const h=r.model;add('總冷卻熱負荷',h.q,'kW');add('冷凝水量',h.condensate,'kg/h');add('總冷卻熱量',h.q*3600,'kJ/h');add('總冷卻熱量（熱化學卡）',h.q*3600/4.184,'kcal/h');add('入口水蒸氣量',h.md*h.wi,'kg/h');add('出口水蒸氣量',h.md*h.wo,'kg/h');add('出口溫度下模型汽化潛熱',2501+(x.cpv-x.cpl)*x.tout,'kJ/kg');add('乾氣體顯熱',h.md*x.cpd*(x.tin-x.tout)/3600,'kW');add('入口全部水蒸氣顯熱',h.md*h.wi*x.cpv*(x.tin-x.tout)/3600,'kW');add('乾空氣質量流率',h.md,'kg/h');add('入口含濕比',h.wi,'kg/kg乾空氣');add('出口含濕比',h.wo,'kg/kg乾空氣');add('入口飽和蒸氣壓',h.pin,'kPa');add('出口飽和蒸氣壓',h.pout,'kPa');add('顯熱分項',h.sensible,'kW');add('冷凝潛熱分項',h.latent,'kW');if(x.tin>50)r.notes.push('高溫飽和廢氣：此結果為理想混合氣工程初估，並非真實氣體精密物性結果。');break;}
case'water':case'gas':{const hot=read(state,'heat'),h=get('heat').model,e=exchanger(hot,h,x,id==='water');add('熱交換負荷',h.q,'kW');add('冷側出口溫度',e.tout,'°C');add('所需冷側流量',e.flow,id==='water'?'m³/h':'Nm³/h');add('冷側質量流率',e.mass,'kg/h');add('冷側溫升',e.tout-x.tin,'K');if(id==='water')add('冷卻水體積流率',e.flow*1000/60,'L/min');add('熱端溫差',hot.tin-e.tout,'K');add('冷端溫差',hot.tout-x.tin,'K');add('端點 LMTD 面積（僅對照）',e.endArea,'m²');add('分段模型換熱面積',e.area,'m²');add('最小局部溫差',e.minDelta,'K');add('端點對數平均溫差',e.endLm,'K');r.notes.push('面積為固定 U、理想逆流初估；冷凝廢氣不直接以端點平均溫差作最終選型。');break;}
}cache[id]=r;return r;}catch(e){cache[id]={error:e.message,rows:[],notes:[]};throw e;}}
for(const s of sections){try{get(s.id);}catch{}}return cache;}
const api={sections,defaults,calculate,psat,humidity,lmtd,friction,heatModel,exchanger,read};if(typeof module!=='undefined'&&module.exports)module.exports=api;root.Engine=api;
})(typeof window!=='undefined'?window:globalThis);
