const assert=require('node:assert/strict'),fs=require('node:fs'),E=require('./engine.js');
let passed=0;const report=[];
function test(name,fn){try{fn();passed++;report.push('PASS '+name);}catch(e){report.push('FAIL '+name+' — '+e.message);console.error(report.join('\n'));process.exit(1);}}
function near(a,b,tol=1e-9){assert.ok(Number.isFinite(a)&&Math.abs(a-b)<=tol*Math.max(1,Math.abs(b)),`${a} != ${b}`);}
const value=(r,id,label)=>{assert.ok(!r[id].error,r[id].error);const v=r[id].rows.find(x=>x.label===label);assert.ok(v,`${id}: ${label}`);return v.value;};
const d=E.defaults(),r=E.calculate(d);
test('13 modules have valid default calculations',()=>{assert.equal(E.sections.length,13);for(const s of E.sections)assert.ok(!r[s.id].error,r[s.id].error);});
test('IAPWS saturation pressure at triple point',()=>near(E.psat(.01),.611657,1e-5));
test('IAPWS saturation pressure at 100 C',()=>near(E.psat(100),101.41799,1e-6));
test('Steam table checkpoints 40 C / 90 C',()=>{near(E.psat(40),7.3851,2e-5);near(E.psat(90),70.1827,2e-6);});
test('Laminar Darcy coefficient',()=>near(E.friction(1000,.0001),.064));
test('Transitional pipe flow rejected',()=>assert.throws(()=>E.friction(3000,.001),/轉捩/));
test('Turbulent coefficient benchmark',()=>near(E.friction(1e5,.0001),.0184524453,1e-8));
test('PM unit conversions',()=>{near(r.base.load,21.6);near(value(r,'base','每年粒狀物'),103680);});
test('Continuity with selected pipe diameter',()=>{const s=E.defaults();s.duct.diameter=1;near(value(E.calculate(s),'duct','實際風速'),20/Math.PI);});
test('Cyclone geometry and cut size reference',()=>{near(value(r,'cyclone','單台筒徑'),5/3);near(value(r,'cyclone','切割粒徑 d₅₀'),6.94506593245,1e-8);});
test('Particle diameter equals d50 gives 50 percent grade efficiency',()=>{const s=E.defaults();s.base.dp=value(r,'cyclone','切割粒徑 d₅₀');near(value(E.calculate(s),'cyclone','代表粒徑分級效率'),50);});
test('Known-efficiency mode requires a provided bulk efficiency',()=>{const s=E.defaults();s.cyclone.mode=1;const v=E.calculate(s);assert.equal(v.summary.c,null);assert.equal(value(v,'cyclone','單機 PM 捕集量'),null);});
test('Known PM chain and mass conservation',()=>{const s=E.defaults();s.cyclone.mode=1;s.cyclone.eta=80;s.bag.eta=90;s.esp.on=0;const v=E.calculate(s);near(v.summary.c,24);near(value(v,'stack','粒狀物排放率'),.12);near(value(v,'stack','PM 年排放量'),2073.6);});
test('Stack volume corrects temperature and conserves pollutant mass',()=>{const s=E.defaults();s.cyclone.on=0;const v=E.calculate(s),q=value(v,'stack','出口實際風量'),c=value(v,'stack','粒狀物出口濃度');near(q,18000*308.15/333.15);near(q*c,18000*v.summary.c);});
test('Measured stack flow override',()=>{const s=E.defaults();s.stack.q=20000;near(value(E.calculate(s),'stack','出口實際風量'),20000);});
test('Bag count rounds up and installed area meets design',()=>{near(value(r,'bag','濾袋數量'),146);assert.ok(value(r,'bag','實裝過濾面積')>=220);near(value(r,'bag','PM 捕集量'),21.492);});
test('ESP target without area margin',()=>{const s=E.defaults();s.esp.margin=1;near(value(E.calculate(s),'esp','設計面積下預估效率'),99);});
test('HCl NaOH molar balance',()=>{near(value(r,'scrub','污染物去除量'),8.55);near(value(r,'scrub','理論純藥劑量'),8.55/36.46*40);near(value(r,'scrub','設計純藥劑量'),14.0702139331,1e-9);});
test('Carbon mass, capacity and service time',()=>{near(value(r,'carbon','活性碳裝填量'),2400);near(value(r,'carbon','未折減容量使用時間'),192/4.86);near(value(r,'carbon','折減後容量使用時間'),134.4/4.86);});
test('Zero carbon loading does not return zero service time',()=>{const s=E.defaults();s.carbon.cin=0;assert.equal(value(E.calculate(s),'carbon','折減後容量使用時間'),null);});
test('Motor shaft vs electrical power',()=>{near(r.fan.electric*.9,r.fan.motorShaft);near(r.fan.motorShaft*.95*.7,5*r.fan.pressure/1000);});
test('Disabled devices do not contribute pressure',()=>{const s=E.defaults();for(const m of ['duct','cyclone','bag','esp','scrub','carbon'])s[m].on=0;near(E.calculate(s).fan.pressure,345);});
test('Zero PM input has no division by zero',()=>{const s=E.defaults();s.base.pm=0;s.cyclone.on=0;const v=E.calculate(s);near(v.summary.c,0);assert.equal(value(v,'summary','串聯粒狀物去除效率'),null);});
test('Heat dry-air/water mass balance',()=>{const h=r.heat.model;near(h.md*h.wi,h.md*h.wo+h.condensate);});
test('Heat independent inlet/outlet enthalpy balance',()=>{const x=d.heat,h=r.heat.model;const inlet=h.md*x.cpd*x.tin+h.md*h.wi*(2501+x.cpv*x.tin);const outlet=h.md*x.cpd*x.tout+h.md*h.wo*(2501+x.cpv*x.tout)+h.condensate*x.cpl*x.tout;near(h.q,(inlet-outlet)/3600);near(h.q,h.sensible+h.latent);});
test('Heat is linear in dry normal volume',()=>{const s=E.defaults();s.heat.q*=2;near(E.calculate(s).heat.model.q,r.heat.model.q*2);});
test('Counterflow water energy balance',()=>{const flow=value(r,'water','所需冷側流量');near(flow*1000*4.186*10/3600,r.heat.model.q);});
test('Counterflow allows cold outlet above hot outlet',()=>{const s=E.defaults();s.water.tout=60;assert.ok(!E.calculate(s).water.error);});
test('Both water operating modes agree',()=>{const s=E.defaults();s.water.mode=1;s.water.flow=value(r,'water','所需冷側流量');near(value(E.calculate(s),'water','冷側出口溫度'),35);});
test('Both gas operating modes agree',()=>{const s=E.defaults();s.gas.mode=0;s.gas.tout=value(r,'gas','冷側出口溫度');near(value(E.calculate(s),'gas','所需冷側流量'),90000);});
test('Inactive cold flow input can be blank',()=>{const s=E.defaults();s.water.flow='';assert.ok(!E.calculate(s).water.error);});
test('Equal terminal temperature differences are stable',()=>near(E.lmtd(20,20),20));
test('Nonpositive terminal approach rejected',()=>assert.throws(()=>E.lmtd(20,0),/溫差/));
test('Hot temperature inversion rejected',()=>{const s=E.defaults();s.heat.tout=95;assert.match(E.calculate(s).heat.error,/入口溫度/);});
test('Saturation at or above total pressure rejected',()=>{const s=E.defaults();s.heat.p=50;assert.match(E.calculate(s).heat.error,/蒸氣壓/);});
test('100 percent ESP and scrubber targets rejected',()=>{const s=E.defaults();s.esp.eta=100;s.scrub.eta=100;const v=E.calculate(s);assert.ok(v.esp.error&&v.scrub.error);});
test('Negative, empty, NaN and Infinity inputs rejected',()=>{for(const raw of [-1,'','NaN','Infinity']){const s=E.defaults();s.base.q=raw;assert.ok(E.calculate(s).base.error);}});
test('Discrete counts and mode values validated',()=>{const s=E.defaults();s.cyclone.n=1.5;s.water.mode=.5;const v=E.calculate(s);assert.ok(v.cyclone.error&&v.water.error);});
test('No cross-tool dependency: invalid air does not break heat',()=>{const s=E.defaults();s.base.q='';assert.ok(!E.calculate(s).heat.error);});
test('Segmented area convergence 1000 vs 2000 intervals',()=>{for(const id of ['water','gas']){const x=E.read(d,id),h=r.heat.model;const a=E.exchanger(d.heat,h,x,id==='water',1000),b=E.exchanger(d.heat,h,x,id==='water',2000);near(a.area,b.area,2e-6);}});
test('Segmented area scales inversely with U',()=>{const s=E.defaults();s.water.u=120;near(value(E.calculate(s),'water','分段模型換熱面積'),value(r,'water','分段模型換熱面積')/2);});
test('All returned default numeric values are finite',()=>{for(const section of Object.values(r))for(const row of section.rows)assert.ok(row.value===null||Number.isFinite(row.value));});

test('Default stack all four PM results are numerical estimates',()=>{near(value(r,'stack','PM 排放量'),0.00022173224136422026,1e-12);near(value(r,'stack','PM 年排放量'),1.0643147585482573,1e-10);near(value(r,'stack','粒狀物出口濃度'),.013317845964355379,1e-12);near(value(r,'stack','粒狀物排放率'),.00006159228926783896,1e-12);assert.equal(r.stack.estimated,true);});
test('Measured efficiency disables estimated-basis marker',()=>{const s=E.defaults();s.cyclone.mode=1;s.cyclone.eta=80;const v=E.calculate(s);assert.equal(v.stack.estimated,false);assert.equal(v.summary.estimated,false);});
test('Missing measured cyclone efficiency explains stack dependency',()=>{const s=E.defaults();s.cyclone.mode=1;const v=E.calculate(s);assert.ok(v.stack.notes.some(n=>n.includes('缺少上游')));});
test('Zero and complete cyclone capture conserve mass',()=>{for(const eta of [0,100]){const s=E.defaults();s.cyclone.mode=1;s.cyclone.eta=eta;s.bag.on=0;s.esp.on=0;const v=E.calculate(s);near(value(v,'stack','PM 排放量'),21.6*(1-eta/100));}});
test('All stack inputs preserve mass and annual-time relationship',()=>{for(const [key,num]of [['t',80],['p',95],['q',24000],['v',20],['height',30]]){const s=E.defaults();s.stack[key]=num;const v=E.calculate(s),q=value(v,'stack','出口實際風量'),c=value(v,'stack','粒狀物出口濃度'),mass=value(v,'stack','PM 排放量');near(q*c/1e6,mass);near(value(v,'stack','PM 年排放量'),mass*16*300);near(value(v,'stack','粒狀物排放率')*3.6,mass);}});

const text=`${passed} tests passed\n${report.join('\n')}\n`;fs.writeFileSync(__dirname+'/TEST-RESULTS.txt',text);console.log(text);
